#!/usr/bin/env bash
# Concatenate all Apps Script source files into dist/Code.gs for one-paste deploys.
set -euo pipefail
cd "$(dirname "$0")/.."
out=dist/Code.gs
{
  echo "// LVP Deck Sync — single-file bundle. Generated by scripts/build-bundle.sh."
  echo "// Source of truth is appsscript/*.js in the repo; regenerate rather than editing here."
  for f in Config Util SheetSource DeckIndex SlideOps GlanceTable CoverStats Bootstrap Main; do
    echo ""
    echo "// ═══════════════════════════════ $f.js ═══════════════════════════════"
    echo ""
    cat "appsscript/$f.js"
  done
} > "$out"
echo "Wrote $out ($(wc -l < "$out") lines)"
